// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLr-yARHQOIEvhBBb7sg_sIo3x8ZkXhE',
    appId: '1:14808710235:web:1020ad9ffc5a46a67f537e',
    messagingSenderId: '14808710235',
    projectId: 'monthly-d9c70',
    authDomain: 'monthly-d9c70.firebaseapp.com',
    storageBucket: 'monthly-d9c70.appspot.com',
    measurementId: 'G-NL3D2JLZGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCeHV-34RbHjbqp-v8gS242OEIrSpxQXs',
    appId: '1:14808710235:android:e454e6c4862006d67f537e',
    messagingSenderId: '14808710235',
    projectId: 'monthly-d9c70',
    storageBucket: 'monthly-d9c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoYxGJoddd4Zn-E2xCWduwjlr2GOpAnX8',
    appId: '1:14808710235:ios:ce292f565fd225e57f537e',
    messagingSenderId: '14808710235',
    projectId: 'monthly-d9c70',
    storageBucket: 'monthly-d9c70.appspot.com',
    iosClientId: '14808710235-llspa9k028555opg71lh8as43ftalpbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.monthly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoYxGJoddd4Zn-E2xCWduwjlr2GOpAnX8',
    appId: '1:14808710235:ios:303c1f5739aae3c07f537e',
    messagingSenderId: '14808710235',
    projectId: 'monthly-d9c70',
    storageBucket: 'monthly-d9c70.appspot.com',
    iosClientId: '14808710235-ao67tfo76ji6nrig40picr9unaae4osn.apps.googleusercontent.com',
    iosBundleId: 'com.example.monthly.RunnerTests',
  );
}
